name: CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Load Environment Variables
        run: npx -p dotenv

      - name: Set Environment Variables
        run: |
          echo "DB_HOST=$DB_HOST"
          echo "DB_USER=$DB_TEST_USER"
          echo "DB_PASSWORD=$DB_TEST_PASS"
          echo "DB_NAME=$DB_TEST_NAME"

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests
        run: npm test
