name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Set Environment Variables
        run: |
          echo "DB_HOST=process.env.DB_HOST" >> $GITHUB_ENV
          echo "DB_USER=process.env.DB_TEST_USER" >> $GITHUB_ENV
          echo "DB_PASSWORD=process.env.DB_TEST_PASS" >> $GITHUB_ENV
          echo "DB_NAME=process.env.DB_TEST_NAME" >> $GITHUB_ENV

      - name: Build TypeScript
        run: npm run build

      - name: Run Tests
        run: npm test
